.TH client 1 "Sep 2025" "BSDSF23M039-OS-A01" "User Commands"
.SH NAME
client \- demo client that exercises string and file utilities
.SH SYNOPSIS
.B client
.br
.B client_dynamic
.br
.B client_static
.SH DESCRIPTION
The
.B client
program runs tests for string functions (mystrlen, mystrcpy, mystrncpy, mystrcat)
and file functions (wordCount, mygrep). It prints results to standard output.
.SH AUTHOR
Your Name <you@example.com>
